### ISSUE TITLE
Update the GitHub links to the new repo location

### ISSUE THREAD

**Issue by PipGrylls** [Southampton-RSG-Training/git-novice#1]
Could also be worth using this opportunity to change this material (and all materials) to use separated data repositories.

**Comment by smangham** [comment]
This is a good idea, the data itself is all available raw at https://raw.githubusercontent.com/Southampton-RSG-Training/git-novice/gh-pages/code/temp_conversion.py etc., but... Git Bash does not ship with `wget`, only `curl`. So to download both files, we'd need:
```
curl -O https://raw.githubusercontent.com/Southampton-RSG-Training/git-novice/gh-pages/code/temp_conversion.py -O https://raw.githubusercontent.com/Southampton-RSG-Training/git-novice/gh-pages/code/climate_analysis.py
```
Which I guess we can get people to copy-paste. We could download a single zip file, but unzip doesn't accept pipes. The best (?) solution seems to be (as per here: https://www.reddit.com/r/linuxquestions/comments/1ihjjz/piping_a_zip_file_from_curl_to_unzip/):
```
curl https//raw.githubusercontent.com/Southampton-RSG-Training/git-novice/gh-pages/code.tar.gz | tar -xzv
```
Relies a bit heavily on Magic Incantations we don't teach, 

Opinions? @PipGrylls

**Comment by smangham** [comment]
Fixed the URLs.
